(function(){var q;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ca="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=da(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ca(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,h){this.g=g;ca(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=t[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ca(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ea(ba(this))}})}return a});function ea(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var fa="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)x(d,e)&&(a[e]=d[e])}return a};u("Object.assign",function(a){return a||fa});
var ha="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ia=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=ha(e.prototype||Object.prototype);return Function.prototype.apply.call(c,
e,d)||e}}(),ka;if("function"==typeof Object.setPrototypeOf)ka=Object.setPrototypeOf;else{var ma;a:{var na={a:!0},oa={};try{oa.__proto__=na;ma=oa.a;break a}catch(a){}ma=!1}ka=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var pa=ka;
function y(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(pa)pa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.da=b.prototype}function qa(){this.j=!1;this.h=null;this.m=void 0;this.g=1;this.u=0;this.i=null}function ra(a){if(a.j)throw new TypeError("Generator is already running");a.j=!0}qa.prototype.s=function(a){this.m=a};function sa(a,b){a.i={aa:b,ba:!0};a.g=a.u}
qa.prototype.return=function(a){this.i={return:a};this.g=this.u};function ta(a){this.g=new qa;this.h=a}function ua(a,b){ra(a.g);var c=a.g.h;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return wa(a)}
function va(a,b,c,d){try{var e=b.call(a.g.h,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.j=!1,e;var g=e.value}catch(h){return a.g.h=null,sa(a.g,h),wa(a)}a.g.h=null;d.call(a.g,g);return wa(a)}function wa(a){for(;a.g.g;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(c){a.g.m=void 0,sa(a.g,c)}a.g.j=!1;if(a.g.i){b=a.g.i;a.g.i=null;if(b.ba)throw b.aa;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function xa(a){this.next=function(b){ra(a.g);a.g.h?b=va(a,a.g.h.next,b,a.g.s):(a.g.s(b),b=wa(a));return b};this.throw=function(b){ra(a.g);a.g.h?b=va(a,a.g.h["throw"],b,a.g.s):(sa(a.g,b),b=wa(a));return b};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}function ya(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}new Promise(function(d,e){function g(h){h.done?d(h.value):Promise.resolve(h.value).then(b,c).then(g,e)}g(a.next())})}
function za(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}u("Reflect",function(a){return a?a:{}});u("Reflect.construct",function(){return ia});u("Reflect.setPrototypeOf",function(a){return a?a:pa?function(b,c){try{return pa(b,c),!0}catch(d){return!1}}:null});
u("Promise",function(a){function b(h){this.h=0;this.i=void 0;this.g=[];this.u=!1;var f=this.j();try{h(f.resolve,f.reject)}catch(k){f.reject(k)}}function c(){this.g=null}function d(h){return h instanceof b?h:new b(function(f){f(h)})}if(a)return a;c.prototype.h=function(h){if(null==this.g){this.g=[];var f=this;this.i(function(){f.m()})}this.g.push(h)};var e=t.setTimeout;c.prototype.i=function(h){e(h,0)};c.prototype.m=function(){for(;this.g&&this.g.length;){var h=this.g;this.g=[];for(var f=0;f<h.length;++f){var k=
h[f];h[f]=null;try{k()}catch(l){this.j(l)}}}this.g=null};c.prototype.j=function(h){this.i(function(){throw h;})};b.prototype.j=function(){function h(l){return function(m){k||(k=!0,l.call(f,m))}}var f=this,k=!1;return{resolve:h(this.F),reject:h(this.m)}};b.prototype.F=function(h){if(h===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(h instanceof b)this.H(h);else{a:switch(typeof h){case "object":var f=null!=h;break a;case "function":f=!0;break a;default:f=!1}f?this.D(h):this.s(h)}};
b.prototype.D=function(h){var f=void 0;try{f=h.then}catch(k){this.m(k);return}"function"==typeof f?this.I(f,h):this.s(h)};b.prototype.m=function(h){this.A(2,h)};b.prototype.s=function(h){this.A(1,h)};b.prototype.A=function(h,f){if(0!=this.h)throw Error("Cannot settle("+h+", "+f+"): Promise already settled in state"+this.h);this.h=h;this.i=f;2===this.h&&this.G();this.B()};b.prototype.G=function(){var h=this;e(function(){if(h.C()){var f=t.console;"undefined"!==typeof f&&f.error(h.i)}},1)};b.prototype.C=
function(){if(this.u)return!1;var h=t.CustomEvent,f=t.Event,k=t.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof h?h=new h("unhandledrejection",{cancelable:!0}):"function"===typeof f?h=new f("unhandledrejection",{cancelable:!0}):(h=t.document.createEvent("CustomEvent"),h.initCustomEvent("unhandledrejection",!1,!0,h));h.promise=this;h.reason=this.i;return k(h)};b.prototype.B=function(){if(null!=this.g){for(var h=0;h<this.g.length;++h)g.h(this.g[h]);this.g=null}};var g=new c;b.prototype.H=
function(h){var f=this.j();h.J(f.resolve,f.reject)};b.prototype.I=function(h,f){var k=this.j();try{h.call(f,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(h,f){function k(p,r){return"function"==typeof p?function(v){try{l(p(v))}catch(R){m(R)}}:r}var l,m,n=new b(function(p,r){l=p;m=r});this.J(k(h,l),k(f,m));return n};b.prototype.catch=function(h){return this.then(void 0,h)};b.prototype.J=function(h,f){function k(){switch(l.h){case 1:h(l.i);break;case 2:f(l.i);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;null==this.g?g.h(k):this.g.push(k);this.u=!0};b.resolve=d;b.reject=function(h){return new b(function(f,k){k(h)})};b.race=function(h){return new b(function(f,k){for(var l=w(h),m=l.next();!m.done;m=l.next())d(m.value).J(f,k)})};b.all=function(h){var f=w(h),k=f.next();return k.done?d([]):new b(function(l,m){function n(v){return function(R){p[v]=R;r--;0==r&&l(p)}}var p=[],r=0;do p.push(void 0),r++,d(k.value).J(n(p.length-1),m),k=f.next();while(!k.done)})};return b});
u("Object.setPrototypeOf",function(a){return a||pa});
u("WeakMap",function(a){function b(k){this.g=(f+=Math.random()+1).toString();if(k){k=w(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!x(k,h)){var l=new c;ca(k,h,{value:l})}}function g(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(n){return!1}}())return a;var h="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var f=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!x(k,h))throw Error("WeakMap key fail: "+k);k[h][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&x(k,h)?k[h][this.g]:void 0};b.prototype.has=function(k){return d(k)&&x(k,
h)&&x(k[h],this.g)};b.prototype.delete=function(k){return d(k)&&x(k,h)&&x(k[h],this.g)?delete k[h][this.g]:!1};return b});
u("Map",function(a){function b(){var f={};return f.v=f.next=f.head=f}function c(f,k){var l=f[1];return ea(function(){if(l){for(;l.head!=f[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(f,k){var l=k&&typeof k;"object"==l||"function"==l?g.has(k)?l=g.get(k):(l=""+ ++h,g.set(k,l)):l="p_"+k;var m=f[0][l];if(m&&x(f[0],l))for(f=0;f<m.length;f++){var n=m[f];if(k!==k&&n.key!==n.key||k===n.key)return{id:l,list:m,index:f,o:n}}return{id:l,
list:m,index:-1,o:void 0}}function e(f){this[0]={};this[1]=b();this.size=0;if(f){f=w(f);for(var k;!(k=f.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),k=new a(w([[f,"s"]]));if("s"!=k.get(f)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=f||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(n){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(f,k){f=0===f?0:f;var l=d(this,f);l.list||(l.list=this[0][l.id]=[]);l.o?l.o.value=k:(l.o={next:this[1],v:this[1].v,head:this[1],key:f,value:k},l.list.push(l.o),this[1].v.next=l.o,this[1].v=l.o,this.size++);return this};e.prototype.delete=function(f){f=d(this,f);return f.o&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.o.v.next=f.o.next,f.o.next.v=f.o.v,f.o.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].v=b();this.size=0};e.prototype.has=function(f){return!!d(this,f).o};e.prototype.get=function(f){return(f=d(this,f).o)&&f.value};e.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};e.prototype.keys=function(){return c(this,function(f){return f.key})};e.prototype.values=function(){return c(this,function(f){return f.value})};e.prototype.forEach=function(f,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=
m.value,f.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var h=0;return e});function Aa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
function Ba(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.entries",function(a){return a?a:function(){return Ba(this,function(b,c){return[b,c]})}});u("Array.prototype.keys",function(a){return a?a:function(){return Ba(this,function(b){return b})}});
u("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});u("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==Aa(this,b,"includes").indexOf(b,c||0)}});
u("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});u("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(f){return f};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var h=0;!(g=b.next()).done;)e.push(c.call(d,g.value,h++))}else for(g=b.length,h=0;h<g;h++)e.push(c.call(d,b[h],h));return e}});
u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)x(b,d)&&c.push([d,b[d]]);return c}});u("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=Aa(this,b,"startsWith"),e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<g&&c<e;)if(d[c++]!=b[h++])return!1;return h>=g}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var z=this||self;function Ca(a){var b=a.url;a=a.S;this.j=b;this.s=a;a=/[?&]dsh=1(&|$)/.test(b);this.h=!a&&/[?&]ae=1(&|$)/.test(b);this.m=!a&&/[?&]ae=2(&|$)/.test(b);if((this.g=/[?&]adurl=([^&]*)/.exec(b))&&this.g[1]){try{var c=decodeURIComponent(this.g[1])}catch(d){c=null}this.i=c}}function Da(a){var b="&act=1&ri=1";a.h&&a.s&&(b+=Ea(a));return Fa(a,b)}function Ga(a,b){return a.h&&a.i||a.m?1==b?a.h?a.i:Fa(a,"&dct=1"):2==b?Fa(a,"&ri=2"):Fa(a,"&ri=16"):a.j}
function Fa(a,b){return a.g?a.j.slice(0,a.g.index)+b+a.j.slice(a.g.index):a.j+b}
function Ea(a){a=a.s;var b=encodeURIComponent,c="";a.platform&&(c+="&uap="+b(a.platform));a.platformVersion&&(c+="&uapv="+b(a.platformVersion));a.uaFullVersion&&(c+="&uafv="+b(a.uaFullVersion));a.architecture&&(c+="&uaa="+b(a.architecture));a.model&&(c+="&uam="+b(a.model));a.bitness&&(c+="&uab="+b(a.bitness));a.fullVersionList&&(c+="&uafvl="+b(a.fullVersionList.map(function(d){return b(d.brand)+";"+b(d.version)}).join("|")));"undefined"!==typeof a.wow64&&(c+="&uaw="+Number(a.wow64));return c};var Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function Ia(a,b){return a<b?-1:a>b?1:0};function A(a){this.g=a}A.prototype.toString=function(){return this.g.toString()};A.prototype.h=!0;var Ja;try{new URL("s://g"),Ja=!0}catch(a){Ja=!1}var Ka=Ja,La={},Ma=new A("about:invalid#zClosurez",La);var Na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Oa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};
function Pa(a,b){a:{for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]};var Qa,Ra;a:{for(var Sa=["CLOSURE_FLAGS"],Ta=z,Ua=0;Ua<Sa.length;Ua++)if(Ta=Ta[Sa[Ua]],null==Ta){Ra=null;break a}Ra=Ta}var Va=Ra&&Ra[610401301];Qa=null!=Va?Va:!1;function Wa(){var a=z.navigator;return a&&(a=a.userAgent)?a:""}var B,Xa=z.navigator;B=Xa?Xa.userAgentData||null:null;function Ya(a){return Qa?B?B.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function C(a){return-1!=Wa().indexOf(a)};function D(){return Qa?!!B&&0<B.brands.length:!1}function Za(){return D()?!1:C("Opera")}function $a(){return C("Firefox")||C("FxiOS")}function ab(){return D()?Ya("Chromium"):(C("Chrome")||C("CriOS"))&&!(D()?0:C("Edge"))||C("Silk")};function bb(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};/*

 SPDX-License-Identifier: Apache-2.0
*/
function cb(a){this.ca=a}function E(a){return new cb(function(b){return b.substr(0,a.length+1).toLowerCase()===a+":"})}var db=new cb(function(a){return/^[^:]*([/?#]|$)/.test(a)}),eb=E("http"),fb=E("https"),gb=E("ftp"),ib=E("mailto"),jb=E("intent"),kb=E("market"),lb=E("itms"),nb=E("itms-appss"),ob=[E("data"),eb,fb,ib,gb,db];function pb(a){z.setTimeout(function(){throw a;},0)};function qb(){return C("iPhone")&&!C("iPod")&&!C("iPad")};function rb(a){rb[" "](a);return a}rb[" "]=function(){};var sb=Za(),tb=D()?!1:C("Trident")||C("MSIE"),ub=C("Edge"),vb=C("Gecko")&&!(-1!=Wa().toLowerCase().indexOf("webkit")&&!C("Edge"))&&!(C("Trident")||C("MSIE"))&&!C("Edge"),wb=-1!=Wa().toLowerCase().indexOf("webkit")&&!C("Edge"),xb=qb(),yb=C("iPad"),zb;
a:{var Ab="",Bb=function(){var a=Wa();if(vb)return/rv:([^\);]+)(\)|;)/.exec(a);if(ub)return/Edge\/([\d\.]+)/.exec(a);if(tb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(wb)return/WebKit\/(\S+)/.exec(a);if(sb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Bb&&(Ab=Bb?Bb[1]:"");if(tb){var Cb,Db=z.document;Cb=Db?Db.documentMode:void 0;if(null!=Cb&&Cb>parseFloat(Ab)){zb=String(Cb);break a}}zb=Ab}var Eb=zb;var Fb=$a(),Gb=qb()||C("iPod"),Hb=C("iPad"),Ib=C("Android")&&!(ab()||$a()||Za()||C("Silk")),Jb=ab(),Kb=C("Safari")&&!(ab()||(D()?0:C("Coast"))||Za()||(D()?0:C("Edge"))||(D()?Ya("Microsoft Edge"):C("Edg/"))||(D()?Ya("Opera"):C("OPR"))||$a()||C("Silk")||C("Android"))&&!(qb()||C("iPad")||C("iPod"));var Lb={},Mb=null;
function Nb(a,b){void 0===b&&(b=0);if(!Mb){Mb={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var g=c.concat(d[e].split(""));Lb[e]=g;for(var h=0;h<g.length;h++){var f=g[h];void 0===Mb[f]&&(Mb[f]=h)}}}b=Lb[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=g=0;g<a.length-2;g+=3){var k=a[g],l=a[g+1];f=a[g+2];h=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|f>>6];f=b[f&63];c[e++]=h+k+l+f}h=0;f=d;switch(a.length-g){case 2:h=
a[g+1],f=b[(h&15)<<2]||d;case 1:a=a[g],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+f+d}return c.join("")};var Ob="undefined"!==typeof Uint8Array,Pb=!tb&&"function"===typeof btoa;function F(a){return Array.prototype.slice.call(a)};var G="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0,Qb=G?function(a,b){a[G]|=b}:function(a,b){void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Rb(a){var b=H(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=F(a)),I(a,b|1))}
var Sb=G?function(a,b){a[G]&=~b}:function(a,b){void 0!==a.g&&(a.g&=~b)},H=G?function(a){return a[G]|0}:function(a){return a.g|0},J=G?function(a){return a[G]}:function(a){return a.g},I=G?function(a,b){a[G]=b}:function(a,b){void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Tb(a,b){Object.isFrozen(a)&&(a=F(a));I(a,b);return a}function Ub(a){Qb(a,1);return a}function Vb(a){Qb(a,34);return a}function Wb(a,b){I(b,(a|0)&-255)}
function Zb(a,b){I(b,(a|34)&-221)}function $b(a){a=a>>11&1023;return 0===a?536870912:a};var ac={};function bc(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var cc,L,dc=[];I(dc,39);L=Object.freeze(dc);function ec(a,b,c){this.i=0;this.g=a;this.h=b;this.j=c}ec.prototype.next=function(){if(this.i<this.g.length){var a=this.g[this.i++];return{done:!1,value:this.h?this.h.call(this.j,a):a}}return{done:!0,value:void 0}};ec.prototype[Symbol.iterator]=function(){return new ec(this.g,this.h,this.j)};var fc={};function gc(){var a=Error();bb(a,"incident");pb(a)};function hc(a){Number.isFinite(a)||gc();return a}function ic(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return a}function M(a){return null==a||"string"===typeof a?a:void 0}function jc(a,b,c,d){var e=!1;if(null!=a&&"object"===typeof a&&!(e=Array.isArray(a))&&a.L===ac)return a;if(!e)return c?d&2?(a=b[kc])?b=a:(a=new b,Vb(a.l),b=b[kc]=a):b=new b:b=void 0,b;e=c=H(a);0===e&&(e|=d&32);e|=d&2;e!==c&&I(a,e);return new b(a)}
var kc="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():"di";function lc(a){return a}function mc(a,b,c){return"string"===typeof a?a:c?"":void 0};var nc;function N(a,b,c){null==a&&(a=nc);nc=void 0;if(null==a){var d=96;c?(a=[c],d|=512):a=[];b&&(d=d&-2095105|(b&1023)<<11)}else{if(!Array.isArray(a))throw Error();d=H(a);if(d&64)return a;d|=64;if(c&&(d|=512,c!==a[0]))throw Error();a:{c=a;var e=c.length;if(e){var g=e-1,h=c[g];if(bc(h)){d|=256;b=+!!(d&512)-1;e=g-b;1024<=e&&(oc(c,b,h),e=1023);d=d&-2095105|(e&1023)<<11;break a}}b&&(h=+!!(d&512)-1,b=Math.max(b,e-h),1024<b&&(oc(c,h,{}),d|=256,b=1023),d=d&-2095105|(b&1023)<<11)}}I(a,d);return a}
function oc(a,b,c){for(var d=1023+b,e=a.length,g=d;g<e;g++){var h=a[g];null!=h&&h!==c&&(c[g-b]=h)}a.length=d+1;a[d]=c};function O(a,b,c,d){c=void 0===c?lc:c;d=void 0===d?lc:d;var e=ia(Map,[],this.constructor);var g=H(a);g|=64;I(a,g);e.h=g;e.i=b;e.g=c||lc;e.j=e.i?pc:d||lc;for(var h=0;h<a.length;h++){var f=a[h],k=c(f[0],!1,!0),l=f[1];b?void 0===l&&(l=null):l=d(f[1],!1,!0,void 0,void 0,g);Map.prototype.set.call(e,k,l)}return e}y(O,Map);function qc(a){if(a.h&2)throw Error("Cannot mutate an immutable Map");}function rc(a,b){b=void 0===b?sc:b;return tc(a,b)}
function tc(a,b){b=void 0===b?sc:b;var c=[];a=Map.prototype.entries.call(a);for(var d;!(d=a.next()).done;)d=d.value,d[0]=b(d[0]),d[1]=b(d[1]),c.push(d);return c}q=O.prototype;q.clear=function(){qc(this);Map.prototype.clear.call(this)};q.delete=function(a){qc(this);return Map.prototype.delete.call(this,this.g(a,!0,!1))};q.entries=function(){var a=Array.from(Map.prototype.keys.call(this));return new ec(a,uc,this)};q.keys=function(){return Map.prototype.keys.call(this)};
q.values=function(){var a=Array.from(Map.prototype.keys.call(this));return new ec(a,O.prototype.get,this)};q.forEach=function(a,b){var c=this;Map.prototype.forEach.call(this,function(d,e){a.call(b,c.get(e),e,c)})};q.set=function(a,b){qc(this);a=this.g(a,!0,!1);return null==a?this:null==b?(Map.prototype.delete.call(this,a),this):Map.prototype.set.call(this,a,this.j(b,!0,!0,this.i,!1,this.h))};q.has=function(a){return Map.prototype.has.call(this,this.g(a,!1,!1))};
q.get=function(a){a=this.g(a,!1,!1);var b=Map.prototype.get.call(this,a);if(void 0!==b){var c=this.i;return c?(c=this.j(b,!1,!0,c,this.m,this.h),c!==b&&Map.prototype.set.call(this,a,c),c):b}};O.prototype[Symbol.iterator]=function(){return this.entries()};O.prototype.toJSON=void 0;function pc(a,b,c,d,e,g){a=jc(a,d,c,g);e&&(a=vc(a));return a}function sc(a){return a}function uc(a){return[a,this.get(a)]};function wc(a,b){return xc(b)}function xc(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)){if(Ob&&null!=a&&a instanceof Uint8Array){if(Pb){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else a=Nb(a);return a}if(a instanceof O)return rc(a)}}return a};function yc(a,b,c){a=F(a);var d=a.length,e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var g in e)b[g]=c(e[g])}return a}function zc(a,b,c,d,e,g){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&H(a)&1?void 0:g&&H(a)&2?a:Ac(a,b,c,void 0!==d,e,g);else if(bc(a)){var h={},f;for(f in a)h[f]=zc(a[f],b,c,d,e,g);a=h}else a=b(a,d);return a}}
function Ac(a,b,c,d,e,g){var h=d||c?H(a):0;d=d?!!(h&32):void 0;a=F(a);for(var f=0;f<a.length;f++)a[f]=zc(a[f],b,c,d,e,g);c&&c(h,a);return a}function Bc(a){return zc(a,Cc,void 0,void 0,!1,!1)}function Cc(a){return a.L===ac?a.toJSON():a instanceof O?rc(a,Bc):xc(a)};function Dc(a,b,c){c=void 0===c?Zb:c;if(null!=a){if(Ob&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=H(a);return d&2?a:!b||d&68||!(d&32||0===d)?Ac(a,Dc,d&4?Zb:c,!0,!1,!0):(I(a,d|34),a)}a.L===ac?(b=a.l,c=J(b),a=c&2?a:Ec(a,b,c,!0)):a instanceof O&&(b=Vb(tc(a,Dc)),a=new O(b,a.i,a.g,a.j));return a}}function Fc(a){var b=a.l;return Ec(a,b,J(b),!1)}function Ec(a,b,c,d){a=a.constructor;nc=b=Gc(b,c,d);b=new a(b);nc=void 0;return b}
function Gc(a,b,c){var d=c||b&2?Zb:Wb,e=!!(b&32);a=yc(a,b,function(g){return Dc(g,e,d)});Qb(a,32|(c?2:0));return a}function vc(a){var b=a.l,c=J(b);return c&2?Ec(a,b,c,!1):a};function P(a,b){a=a.l;return Hc(a,J(a),b)}function Hc(a,b,c,d){if(-1===c)return null;if(c>=$b(b)){if(b&256)return a[a.length-1][c]}else{var e=a.length;if(d&&b&256&&(d=a[e-1][c],null!=d))return d;b=c+(+!!(b&512)-1);if(b<e)return a[b]}}function Ic(a,b,c){var d=a.l,e=J(d);if(e&2)throw Error();Q(d,e,b,c);return a}
function Q(a,b,c,d,e){var g=$b(b);if(c>=g||e){e=b;if(b&256)g=a[a.length-1];else{if(null==d)return;g=a[g+(+!!(b&512)-1)]={};e|=256}g[c]=d;e!==b&&I(a,e)}else a[c+(+!!(b&512)-1)]=d,b&256&&(a=a[a.length-1],c in a&&delete a[c])}function Jc(a,b,c){return void 0!==Kc(a,b,c,!1)}function Lc(a,b,c){var d=b&2;a=Hc(a,b,c);Array.isArray(a)||(a=L);b=H(a);b&1||Ub(a);d?b&2||Vb(a):b&32&&!(b&2)&&Sb(a,32);return a}var Mc;function Nc(){var a;return null!=(a=Mc)?a:Mc=new O(Vb([]),void 0,void 0,void 0,fc)}
function Oc(a,b,c,d,e,g){var h=b&2;a:{var f=c,k=b&2;c=!1;if(null==f){if(k){a=Nc();break a}f=[]}else if(f.constructor===O){if(0==(f.h&2)||k){a=f;break a}f=tc(f)}else Array.isArray(f)?c=!!(H(f)&2):f=[];if(k){if(!f.length){a=Nc();break a}c||(c=!0,Vb(f))}else if(c){c=!1;k=F(f);for(f=0;f<k.length;f++){var l=k[f]=F(k[f]);Array.isArray(l[1])&&(l[1]=Vb(l[1]))}f=k}c||(H(f)&64?Sb(f,32):32&b&&Qb(f,32));g=new O(f,e,mc,g);Q(a,b,d,g,!1);a=g}if(null==a)return a;!h&&e&&(a.m=!0);return a}
function Pc(a,b){a=a.l;var c=J(a);return Oc(a,c,Hc(a,c,b),b,void 0,mc)}function Kc(a,b,c,d){a=a.l;var e=J(a),g=Hc(a,e,c,d);b=jc(g,b,!1,e);b!==g&&null!=b&&Q(a,e,c,b,d);return b}function S(a,b,c){var d=void 0===d?!1:d;b=Kc(a,b,c,d);if(null==b)return b;a=a.l;var e=J(a);if(!(e&2)){var g=vc(b);g!==b&&(b=g,Q(a,e,c,b,d))}return b}
function Qc(a){var b=a.l,c=J(b);a=!!(c&2);var d=a?1:2,e=Rc,g=!!(c&2),h=Lc(b,c,7);if(h!==L&&H(h)&4)3!==d&&(g?2===d&&(d=H(h),h=F(h),I(h,d),Q(b,c,7,h)):(g=Object.isFrozen(h),1===d?g||Object.freeze(h):(d=H(h),e=d&-35,g&&(h=F(h),d=0,Q(b,c,7,h)),d!==e&&I(h,e)))),b=h;else{var f=h;h=!!(c&2);var k=!!(H(f)&2);g=f;!h&&k&&(f=F(f));var l=c|(k?2:0);k=k||void 0;for(var m=0,n=0;m<f.length;m++){var p=jc(f[m],e,!1,l);void 0!==p&&(k=k||J(p.l)&2,f[n++]=p)}n<m&&(f.length=n);e=f;f=H(e);l=f|5;k=k?l&-9:l|8;f!=k&&(e=Tb(e,
k));f=e;g!==f&&Q(b,c,7,f);(h&&2!==d||1===d)&&Object.freeze(f);b=f}if(!(a||H(b)&8)){for(a=0;a<b.length;a++)c=b[a],d=vc(c),c!==d&&(b[a]=d);Qb(b,8)}return b}function Sc(a,b){a=a.l;var c=J(a),d=c&2,e=Lc(a,c,b),g=H(e);if(!(g&4)){Object.isFrozen(e)&&(g=0,e=F(e),Q(a,c,b,e));for(var h=0,f=0;h<e.length;h++){var k=M(e[h]);null!=k&&(e[f++]=k)}f<h&&(e.length=f);g|=5;d&&(g|=34);I(e,g);g&2&&Object.freeze(e)}!d&&(g&2||Object.isFrozen(e))&&(e=F(e),Qb(e,5),Q(a,c,b,e));return e}
function T(a,b){a=P(a,b);a=null==a?a:"boolean"===typeof a||"number"===typeof a?!!a:void 0;return null!=a?a:!1}function Tc(a,b){var c=void 0===c?0:c;a=ic(P(a,b));return null!=a?a:c}function U(a,b){a=M(P(a,b));return null!=a?a:""}function Uc(a,b,c){a=P(a,b);return null!=a?a:void 0===c?0:c}function Vc(a,b,c){if(null!=c){if("boolean"!==typeof c)throw a=typeof c,Error("Expected boolean but got "+("object"!=a?a:c?Array.isArray(c)?"array":a:"null")+": "+c);c=!!c}return Ic(a,b,c)}
function Wc(a,b,c){if(null!=c){if("number"!==typeof c)throw a=Error(),bb(a,"warning"),a;Number.isFinite(c)||gc()}Ic(a,b,c)}function V(a,b,c){if(null!=c&&"string"!==typeof c)throw Error();return Ic(a,b,c)};function W(a,b,c){this.l=N(a,b,c)}W.prototype.toJSON=function(){if(cc)var a=Xc(this,this.l,!1);else a=Ac(this.l,Cc,void 0,void 0,!1,!1),a=Xc(this,a,!0);return a};function Yc(a){cc=!0;try{return JSON.stringify(a.toJSON(),wc)}finally{cc=!1}}W.prototype.L=ac;W.prototype.toString=function(){return Xc(this,this.l,!1).toString()};
function Xc(a,b,c){var d=a.constructor.M,e=$b(J(c?a.l:b)),g=!1;if(d){if(!c){b=F(b);var h;if(b.length&&bc(h=b[b.length-1]))for(g=0;g<d.length;g++)if(d[g]>=e){Object.assign(b[b.length-1]={},h);break}g=!0}e=b;c=!c;h=J(a.l);a=$b(h);h=+!!(h&512)-1;for(var f,k,l=0;l<d.length;l++)if(k=d[l],k<a){k+=h;var m=e[k];null==m?e[k]=c?L:Ub([]):c&&m!==L&&Rb(m)}else f||(m=void 0,e.length&&bc(m=e[e.length-1])?f=m:e.push(f={})),m=f[k],null==f[k]?f[k]=c?L:Ub([]):c&&m!==L&&Rb(m)}d=b.length;if(!d)return b;var n;if(bc(f=
b[d-1])){a:{var p=f;e={};c=!1;for(var r in p)a=p[r],Array.isArray(a)&&a!=a&&(c=!0),null!=a?e[r]=a:c=!0;if(c){for(var v in e){p=e;break a}p=null}}p!=f&&(n=!0);d--}for(;0<d;d--){f=b[d-1];if(null!=f)break;var R=!0}if(!n&&!R)return b;var K;g?K=b:K=Array.prototype.slice.call(b,0,d);b=K;g&&(b.length=d);p&&b.push(p);return b};function Zc(a){this.l=N(a)}y(Zc,W);function $c(a){this.l=N(a)}y($c,W);function ad(a){this.l=N(a)}y(ad,W);function Rc(a){this.l=N(a)}y(Rc,W);Rc.prototype.K=function(){return U(this,3)};Rc.prototype.R=function(a){Vc(this,5,a)};function X(a){this.l=N(a)}y(X,W);X.prototype.K=function(){return U(this,1)};X.prototype.R=function(a){Vc(this,2,a)};function bd(a){this.l=N(a)}y(bd,W);function cd(a){this.l=N(a)}y(cd,W);cd.M=[6,7];function dd(a){this.l=N(a)}y(dd,W);function ed(a){a=a.l;var b=J(a);return Oc(a,b,Hc(a,b,1),1,cd)}dd.M=[17];function fd(a){this.l=N(a)}y(fd,W);function gd(a){this.l=N(a)}y(gd,W);function hd(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};var id={capture:!0},jd={passive:!0},kd=hd(function(){var a=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a=!0}});z.addEventListener("test",null,b)}catch(c){}return a});function ld(a){return a?a.passive&&kd()?a:a.capture||!1:!1}function md(a,b,c,d){a.addEventListener&&a.addEventListener(b,c,ld(d))};function nd(a,b){if(!(b instanceof A||b instanceof A)){b="object"==typeof b&&b.h?b.g.toString():String(b);b:{var c=b;if(Ka){try{var d=new URL(c)}catch(e){c="https:";break b}c=d.protocol}else c:{d=document.createElement("a");try{d.href=c}catch(e){c=void 0;break c}c=d.protocol;c=":"===c||""===c?"https:":c}}"javascript:"===c&&(b="about:invalid#zClosurez");b=new A(b,La)}a.href=b instanceof A&&b.constructor===A?b.g:"type_error:SafeUrl"};var od=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function pd(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)pd(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}var qd=/#|$/;
function rd(a,b){var c=a.search(qd);a:{var d=0;for(var e=b.length;0<=(d=a.indexOf(b,d))&&d<c;){var g=a.charCodeAt(d-1);if(38==g||63==g)if(g=a.charCodeAt(d+e),!g||61==g||38==g||35==g)break a;d+=e+1}d=-1}if(0>d)return null;e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,-1!==e?e:0).replace(/\+/g," "))};function sd(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}function td(a){a.preventDefault?a.preventDefault():a.returnValue=!1}var ud=[];function vd(){var a=ud;ud=[];a=w(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;try{b()}catch(c){}}}function wd(a){ud.push(a);1==ud.length&&(window.Promise?Promise.resolve().then(vd):window.setImmediate?setImmediate(vd):setTimeout(vd,0))}
function xd(a){var b=Y;"complete"===b.readyState||"interactive"===b.readyState?wd(a):b.addEventListener("DOMContentLoaded",a)}function yd(a){var b=window;"complete"===b.document.readyState?wd(a):b.addEventListener("load",a)}function Dd(a){a=void 0===a?document:a;return a.createElement("img")};function Ed(a,b,c,d){Fd(a,b,void 0===c?null:c,void 0===d?!1:d)}
function Fd(a,b,c,d){var e=!1;e=void 0===e?!1:e;a.google_image_requests||(a.google_image_requests=[]);var g=Dd(a.document);if(c||d){var h=function(f){c&&c(f);if(d){f=a.google_image_requests;var k=Na(f,g);0<=k&&Array.prototype.splice.call(f,k,1)}g.removeEventListener&&g.removeEventListener("load",h,ld());g.removeEventListener&&g.removeEventListener("error",h,ld())};md(g,"load",h);md(g,"error",h)}e&&(g.attributionSrc="");g.src=b;a.google_image_requests.push(g)}
function Gd(a,b){var c=void 0===c?!1:c;var d;if(d=a.navigator)d=a.navigator.userAgent,d=/Chrome/.test(d)&&!/Edge/.test(d)?!0:!1;d&&a.navigator.sendBeacon?a.navigator.sendBeacon(b):Ed(a,b,void 0,c)};var Hd=0;function Id(a){return(a=Jd(a))&&a.getAttribute("data-jc-version")||"unknown"}function Jd(a){var b=document.currentScript;return(b=void 0===b?null:b)&&b.getAttribute("data-jc")===String(a)?b:document.querySelector('[data-jc="'+a+'"]')}
function Kd(a){var b=void 0===b?.01:b;if(!(Math.random()>b)){var c=Jd(a);a="https://"+(c&&"true"===c.getAttribute("data-jc-rcd")?"pagead2.googlesyndication-cn.com":"pagead2.googlesyndication.com")+"/pagead/gen_204?id=jca&jc="+a+"&version="+Id(a)+"&sample="+b;Gd(window,a)}};var Y=document,Ld=window;var Md=[eb,fb,ib,gb,db,kb,lb,jb,nb];function Nd(a,b){if(a instanceof A)return a;var c=Md;c=void 0===c?ob:c;a:{c=void 0===c?ob:c;for(var d=0;d<c.length;++d){var e=c[d];if(e instanceof cb&&e.ca(a)){c=new A(a,La);break a}}c=void 0}c=c||Ma;c===Ma&&b(a);return c}
function Od(a){var b=(Pd()?"http:":"https:")+"//pagead2.googlesyndication.com/pagead/gen_204";return function(c){c={id:"unsafeurl",ctx:a,url:c};var d=[];for(e in c)pd(e,c[e],d);var e=d.join("&");if(e){c=b.indexOf("#");0>c&&(c=b.length);d=b.indexOf("?");if(0>d||d>c){d=c;var g=""}else g=b.substring(d+1,c);c=[b.slice(0,d),g,b.slice(c)];d=c[1];c[1]=e?d?d+"&"+e:e:d;e=c[0]+(c[1]?"?"+c[1]:"")+c[2]}else e=b;navigator.sendBeacon&&navigator.sendBeacon(e,"")}};function Pd(){var a=void 0===a?Ld:a;return"http:"===a.location.protocol}function Qd(a){var b=Y;try{return b.querySelectorAll("*["+a+"]")}catch(c){return[]}};function Rd(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};var Sd=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");function Td(a,b){this.g=a;this.h=b}function Ud(a,b){this.url=a;this.P=!!b;this.depth=null};var Vd=null;function Wd(){var a=void 0===a?z:a;return(a=a.performance)&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()}function Xd(){var a=void 0===a?z:a;return(a=a.performance)&&a.now?a.now():null};function Yd(a,b){var c=Xd()||Wd();this.label=a;this.type=b;this.value=c;this.duration=0;this.taskId=this.slotId=void 0;this.uniqueId=Math.random()};var Z=z.performance,Zd=!!(Z&&Z.mark&&Z.measure&&Z.clearMarks),$d=hd(function(){var a;if(a=Zd){var b;if(null===Vd){Vd="";try{a="";try{a=z.top.location.hash}catch(c){a=z.location.hash}a&&(Vd=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Vd;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});
function ae(){var a=window;this.h=[];this.i=a||z;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.h=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=$d()||(null!=b?b:1>Math.random())}function be(a){a&&Z&&$d()&&(Z.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),Z.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))}ae.prototype.start=function(a,b){if(!this.g)return null;a=new Yd(a,b);b="goog_"+a.label+"_"+a.uniqueId+"_start";Z&&$d()&&Z.mark(b);return a};
ae.prototype.end=function(a){if(this.g&&"number"===typeof a.value){a.duration=(Xd()||Wd())-a.value;var b="goog_"+a.label+"_"+a.uniqueId+"_end";Z&&$d()&&Z.mark(b);!this.g||2048<this.h.length||this.h.push(a)}};function ce(){this.i="&";this.h={};this.j=0;this.g=[]}function de(a,b){var c={};c[a]=b;return[c]}function ee(a,b,c,d,e){var g=[];sd(a,function(h,f){(h=fe(h,b,c,d,e))&&g.push(f+"="+h)});return g.join(b)}
function fe(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var g=[],h=0;h<a.length;h++)g.push(fe(a[h],b,c,d+1,e));return g.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(ee(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}
function ge(a,b){var c="https://pagead2.googlesyndication.com"+b,d=he(a)-b.length;if(0>d)return"";a.g.sort(function(m,n){return m-n});b=null;for(var e="",g=0;g<a.g.length;g++)for(var h=a.g[g],f=a.h[h],k=0;k<f.length;k++){if(!d){b=null==b?h:b;break}var l=ee(f[k],a.i,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;c+=l;e=a.i;break}b=null==b?h:b}}a="";null!=b&&(a=e+"trn="+b);return c+a}function he(a){var b=1,c;for(c in a.h)b=c.length>b?c.length:b;return 3997-b-a.i.length-1};function ie(){var a=je;this.pinger=ke;this.g=void 0===a?null:a;this.h=null;this.i=!1;this.m=this.j}function le(a,b){var c=me;try{if(c.g&&c.g.g){var d=c.g.start(a.toString(),3);var e=b();c.g.end(d)}else e=b()}catch(f){b=!0;try{be(d),b=c.m(a,new Rd(f,{message:ne(f)}),void 0,void 0)}catch(k){c.j(217,k)}if(b){var g,h;null==(g=window.console)||null==(h=g.error)||h.call(g,f)}else throw f;}return e}
function oe(a,b){return function(){var c=za.apply(0,arguments);return le(a,function(){return b.apply(void 0,c)})}}
ie.prototype.j=function(a,b,c,d,e){e=e||"jserror";try{var g=new ce;g.g.push(1);g.h[1]=de("context",a);b.error&&b.meta&&b.id||(b=new Rd(b,{message:ne(b)}));if(b.msg){var h=b.msg.substring(0,512);g.g.push(2);g.h[2]=de("msg",h)}var f=b.meta||{};if(this.h)try{this.h(f)}catch(la){}if(d)try{d(f)}catch(la){}b=[f];g.g.push(3);g.h[3]=b;d=z;b=[];h=null;do{var k=d;try{var l;if(l=!!k&&null!=k.location.href)b:{try{rb(k.foo);l=!0;break b}catch(la){}l=!1}var m=l}catch(la){m=!1}if(m){var n=k.location.href;h=k.document&&
k.document.referrer||null}else n=h,h=null;b.push(new Ud(n||""));try{d=k.parent}catch(la){d=null}}while(d&&k!=d);n=0;for(var p=b.length-1;n<=p;++n)b[n].depth=p-n;k=z;if(k.location&&k.location.ancestorOrigins&&k.location.ancestorOrigins.length==b.length-1)for(p=1;p<b.length;++p){var r=b[p];r.url||(r.url=k.location.ancestorOrigins[p-1]||"",r.P=!0)}var v=new Ud(z.location.href,!1);k=null;var R=b.length-1;for(r=R;0<=r;--r){var K=b[r];!k&&Sd.test(K.url)&&(k=K);if(K.url&&!K.P){v=K;break}}K=null;var Re=b.length&&
b[R].url;0!=v.depth&&Re&&(K=b[R]);var aa=new Td(v,K);if(aa.h){var Se=aa.h.url||"";g.g.push(4);g.h[4]=de("top",Se)}var Xb={url:aa.g.url||""};if(aa.g.url){var Yb=aa.g.url.match(od),zd=Yb[1],Ad=Yb[3],Bd=Yb[4];v="";zd&&(v+=zd+":");Ad&&(v+="//",v+=Ad,Bd&&(v+=":"+Bd));var Cd=v}else Cd="";Xb=[Xb,{url:Cd}];g.g.push(5);g.h[5]=Xb;pe(this.pinger,e,g,this.i,c)}catch(la){try{pe(this.pinger,e,{context:"ecmserr",rctx:a,msg:ne(la),url:aa&&aa.g.url},this.i,c)}catch(uf){}}return!0};
function ne(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;var c=b;try{-1==a.indexOf(c)&&(a=c+"\n"+a);for(var d;a!=d;)d=a,a=a.replace(RegExp("((https?:/..*/)[^/:]*:\\d+(?:.|\n)*)\\2"),"$1");b=a.replace(RegExp("\n *","g"),"\n")}catch(e){b=c}}return b};function qe(){};function re(){this.g=Math.random()}function se(){var a=ke,b=window.google_srt;0<=b&&1>=b&&(a.g=b)}function pe(a,b,c,d,e){if(((void 0===d?0:d)?a.g:Math.random())<(e||.01))try{if(c instanceof ce)var g=c;else g=new ce,sd(c,function(f,k){var l=g,m=l.j++;f=de(k,f);l.g.push(m);l.h[m]=f});var h=ge(g,"/pagead/gen_204?id="+b+"&");h&&Ed(z,h)}catch(f){}};var ke,me,je=new ae;function te(){if(!window.google_measure_js_timing){var a=je;a.g=!1;a.h!=a.i.google_js_reporting_queue&&($d()&&Oa(a.h,be),a.h.length=0)}}(function(a){ke=null!=a?a:new re;"number"!==typeof window.google_srt&&(window.google_srt=Math.random());se();me=new ie;me.h=function(b){var c=Hd;0!==c&&(b.jc=String(c),b.shv=Id(c))};me.i=!0;"complete"==window.document.readyState?te():je.g&&md(window,"load",function(){te()})})();function ue(a,b){return oe(a,b)}
function ve(a){var b="O";qe.O&&qe.hasOwnProperty(b)||(b=new qe,qe.O=b);b=[];!a.eid&&b.length&&(a.eid=b.toString());pe(ke,"gdn-asoch",a,!0)};function we(){var a=void 0===a?z:a;return a.oneAfmaInstance};function xe(a){return(a=a.exec(Wa()))?a[1]:""}
var ye=function(){if(Fb)return xe(/Firefox\/([0-9.]+)/);if(tb||ub||sb)return Eb;if(Jb){if(qb()||C("iPad")||C("iPod")||(Qa&&B&&B.platform?"macOS"===B.platform:C("Macintosh"))){var a=xe(/CriOS\/([0-9.]+)/);if(a)return a}return xe(/Chrome\/([0-9.]+)/)}if(Kb&&!(qb()||C("iPad")||C("iPod")))return xe(/Version\/([0-9.]+)/);if(Gb||Hb){if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Wa()))return a[1]+"."+a[2]}else if(Ib)return(a=xe(/Android\s+([0-9.]+)/))?a:xe(/Version\/([0-9.]+)/);return""}();function ze(a,b){b=U(a,2)||b;if(!b)return"";if(T(a,13))return b;var c=/[?&]adurl=([^&]+)/.exec(b);if(!c)return b;var d=[b.slice(0,c.index+1)];Pc(a,4).forEach(function(e,g){d.push(encodeURIComponent(g)+"="+encodeURIComponent(e)+"&")});d.push(b.slice(c.index+1));return d.join("")}
function Ae(a,b){b=void 0===b?[]:b;b=0<b.length?b:Qd("data-asoch-targets");a=ed(a);for(var c=[],d=0;d<b.length;++d){for(var e=b[d].getAttribute("data-asoch-targets"),g=e.split(","),h=!0,f=w(g),k=f.next();!k.done;k=f.next())if(!a.has(k.value)){h=!1;break}if(h){h=a.get(g[0]);for(e=1;e<g.length;++e){f=a.get(g[e]);h=Fc(h).toJSON();f=f.toJSON();k=Math.max(h.length,f.length);for(var l=0;l<k;++l)null==h[l]&&(h[l]=f[l]);h=new cd(h)}g=Pc(h,4);null!=P(h,5)&&g.set("nb",Uc(h,5,0).toString());c.push({element:b[d],
data:h})}else ve({type:1,data:e})}return c}function Be(a,b,c,d){c=ze(b,c);if(0!==c.length){if("2"===rd(c,"ase")&&1087!==d){var e=609===d,g,h=!(null==(g=Y.featurePolicy)||!g.allowedFeatures().includes("attribution-reporting"));g=e?4:h?6:5;var f="";e||h&&!Ce(c)?(c=De(c,"nis",g.toString()),a.setAttribute("attributionsrc",f)):h&&Ce(c)&&(f=De(Da(new Ca({url:c})),"nis",g.toString()),a.setAttribute("attributionsrc",f))}nd(a,Nd(c,Od(d)));a.target||(a.target=null!=M(P(b,11))?U(b,11):"_top")}}
function Ee(a){var b=void 0===b?"":b;var c=void 0===c?!1:c;a=w(a);for(var d=a.next();!d.done;d=a.next()){var e=d.value;d=e.data;var g=0===b.length?!1:e.element.matches(b);"A"!=e.element.tagName||T(d,1)||g||(e=e.element,Be(e,d,e.href,c?1087:609))}}function Ce(a){return!/[?&]dsh=1(&|$)/.test(a)&&/[?&]ae=1(&|$)/.test(a)}
function Fe(a){var b=we();if(b){a=w(a);for(var c=a.next();!c.done;c=a.next())if((c=c.value.data)&&Jc(c,bd,8)){var d=U(S(c,bd,8),4);if(d){b.fetchAppStoreOverlay(d,void 0,U(S(c,bd,8),6));break}}}}
function Ge(a,b){function c(f,k){if(k){f=w(e);for(var l=f.next();!l.done;l=f.next())l=l.value,k[l.K()]&&l.R(!0)}}b=void 0===b?500:b;var d=[],e=[];a=w(a);for(var g=a.next();!g.done;g=a.next())(g=g.value.data)&&Jc(g,X,12)&&(e.push(S(g,X,12)),d.push(S(g,X,12).K()));a=we();d=w(d);for(g=d.next();!g.done;g=d.next()){g=g.value;var h=void 0;null==(h=a)||h.canOpenAndroidApp(g,c,function(){},b)}}
function He(a,b,c,d,e){function g(l){return Gd(Ld,l)}function h(l){return d.openStoreOverlay(l,void 0,U(f,6))}if(!b||!Jc(b,bd,8))return!1;var f=S(b,bd,8),k=U(f,2);Pc(b,10).forEach(function(l,m){var n=k;m=encodeURIComponent(m);var p=encodeURIComponent(l);l=new RegExp("[?&]"+m+"=([^&]+)");var r=l.exec(n);console.log(r);m=m+"="+p;k=r?n.replace(l,r[0].charAt(0)+m):n.replace("?","?"+m+"&")});Ie(b)&&T(b,15)&&!/[?&]label=/.test(c)&&(c=De(c,"label","deep_link_fallback"));return d.redirectForStoreU2({clickUrl:c,
trackingUrl:U(f,3),finalUrl:k,pingFunc:T(b,13)?d.httpTrack:e?g:d.click,openFunc:(null==a?0:T(a,1))?h:d.openIntentOrNativeApp,isExternalClickUrl:T(b,13)})}function Je(a,b){b=void 0===b?null:b;if(null!==b){var c=new Ca({url:a});if(c.h&&c.i||c.m)return b(Da(c)),Ga(c,1)}else return b=new Ca({url:a,S:{}.S}),b.h&&b.i||b.m?navigator.sendBeacon?navigator.sendBeacon(Da(b),"")?Ga(b,1):Ga(b,2):Ga(b,0):a;return a}
function Ke(a,b){(void 0===b||b)&&Ld.fetch?Ld.fetch(a,{method:"GET",keepalive:!0,mode:"no-cors"}).then(function(c){c.ok||Ed(Ld,a)}):Ed(Ld,a)}function De(a,b,c){b=encodeURIComponent(String(b));c=encodeURIComponent(String(c));return a.replace("?","?"+b+"="+c+"&")}function Ie(a){a=w(Qc(a));for(var b=a.next();!b.done;b=a.next())if(b=b.value,3===Uc(b,1,0)&&U(b,2))return!0;return!1};function Le(a,b){return a&&(a=a.match(b+"=([^&]+)"))&&2==a.length?a[1]:""};function Me(a){this.l=N(a)}y(Me,W);function Ne(a){this.l=N(a)}y(Ne,W);function Oe(a,b){return V(a,2,b)}function Pe(a,b){return V(a,3,b)}function Qe(a,b){return V(a,4,b)}function Te(a,b){return V(a,5,b)}function Ue(a,b){return V(a,9,b)}function Ve(a,b){var c=a.l,d=J(c);if(d&2)throw Error();if(null!=b){for(var e=!!b.length,g=0;g<b.length;g++){var h=b[g];e=e&&!(H(h.l)&2)}g=H(b);h=g|1;h=(e?h|8:h&-9)|4;h!=g&&(b=Tb(b,h))}null==b&&(b=void 0);Q(c,d,10,b);return a}function We(a,b){return Vc(a,11,b)}function Xe(a,b){return V(a,1,b)}
function Ye(a,b){return Vc(a,7,b)}Ne.M=[10,6];var Ze="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function $e(a){var b;return null!=(b=a.google_tag_data)?b:a.google_tag_data={}}function af(a){var b,c;return"function"===typeof(null==(b=a.navigator)?void 0:null==(c=b.userAgentData)?void 0:c.getHighEntropyValues)}
function bf(){var a=window;if(!af(a))return null;var b=$e(a);if(b.uach_promise)return b.uach_promise;a=a.navigator.userAgentData.getHighEntropyValues(Ze).then(function(c){null!=b.uach||(b.uach=c);return c});return b.uach_promise=a}
function cf(a){var b;return We(Ve(Te(Oe(Xe(Qe(Ye(Ue(Pe(new Ne,a.architecture||""),a.bitness||""),a.mobile||!1),a.model||""),a.platform||""),a.platformVersion||""),a.uaFullVersion||""),(null==(b=a.fullVersionList)?void 0:b.map(function(c){var d=new Me;d=V(d,1,c.brand);return V(d,2,c.version)}))||[]),a.wow64||!1)}function df(){var a,b;return null!=(b=null==(a=bf())?void 0:a.then(function(c){return cf(c)}))?b:null};function ef(a){var b=this;this.u=Gb||xb||Hb||yb;var c=Qd("data-asoch-meta");if(1!==c.length)ve({type:2,data:c.length});else{this.G=70;this.h=new dd(JSON.parse(c[0].getAttribute("data-asoch-meta"))||[]);this.D=a["extra-meta"]?new dd(JSON.parse(a["extra-meta"])):null;this.F="true"===a["is-fsn"];this.V="true"===a["is-tap-disabled-for-fsn"];this.m=a["ios-store-overlay-config"]?new fd(JSON.parse(a["ios-store-overlay-config"])):null;this.Y="true"===a["use-cct-over-browser"];this.W="true"===a["send-ac-click-ping-by-js"];
this.N="true"===a["correct-redirect-url-for-och-15-click"];this.X="true"===a["send-click-ping-by-js-in-och"];this.T="true"===a["middle-clicks-in-och"];this.C="true"===a["default-msg-in-och"];this.U="true"===a["enable-paw"];this.s="";c=df();null!=c&&c.then(function(e){e=Yc(e);for(var g=[],h=0,f=0;f<e.length;f++){var k=e.charCodeAt(f);255<k&&(g[h++]=k&255,k>>=8);g[h++]=k}e=Nb(g,3);b.s=e});this.g=Ae(this.h);this.C&&(this.j=null,ed(this.h).forEach(function(e){null==b.j&&null!=M(P(e,2))&&null!=M(P(e,9))&&
(b.j=e)}));this.Z=Number(a["deeplink-and-android-app-validation-timeout"])||500;this.H=-Infinity;this.i=U(this.h,5)||"";this.I=T(this.h,11);this.D&&(this.I=T(this.D,11));this.B=this.A=null;T(this.h,3)||(Ee(this.g),Vc(this.h,3,!0));ff(this.g);a=we();!this.u&&a&&Ge(this.g,this.Z);var d;if(a&&(null==(d=this.m)?0:T(d,2)))switch(d=function(){var e=Tc(b.m,4);0<e?z.setTimeout(function(){Fe(b.g)},e):Fe(b.g)},Uc(this.m,3,0)){case 1:a.runOnOnShowEvent(d);break;case 2:yd(d);break;default:Fe(this.g)}md(Y,"click",
ue(557,function(e){gf(b,e)}),id);this.T&&md(Y,"auxclick",ue(557,function(e){1===e.button&&gf(b,e)}),id);this.i&&"function"===typeof window.ss&&md(Y.body,"mouseover",ue(626,function(){window.ss(b.i,0)}),jd);"function"===typeof window.ivti&&window.ivti(Y.body);d=window;d.googqscp&&"function"===typeof d.googqscp.registerCallback&&d.googqscp.registerCallback(function(e,g){b.A=e;b.B=g})}}
function gf(a,b){if(!b.defaultPrevented||a.A===b){for(var c,d,e=b.target;(!c||!d)&&e;){d||"A"!=e.tagName||(d=e);var g=e.hasAttribute("data-asoch-targets"),h=e.hasAttribute("data-asoch-fixed-value");if(!c)if(h)c=new cd(JSON.parse(e.getAttribute("data-asoch-fixed-value"))||[]);else if("A"==e.tagName||g)if(g=g&&"true"===e.getAttribute("data-asoch-is-dynamic")?Ae(a.h,[e]):a.g,g=hf(g,e))c=g.data;e=e.parentElement}e=c&&!T(c,1);if(a.C&&a.j&&b.defaultPrevented)jf(a,b,d,e?c:a.j);else{if(e){if(!a.C&&b.defaultPrevented){jf(a,
b,d,c);return}g=w(Sc(c,6));for(h=g.next();!h.done;h=g.next())Ke(h.value)}if(d&&e){c=e?c:null;(e=hf(a.g,d))?e=e.data:(e=new cd,V(e,2,d.href),V(e,11,d.target||"_top"),a.g.push({element:d,data:e}));Be(d,c||e,U(e,2),557);kf(a,b,d,c);e=w(Sc(a.h,17));for(h=e.next();!h.done;h=e.next()){g=void 0;var f=h.value,k=Y.body;g=void 0===g?{}:g;"function"===typeof window.CustomEvent?h=new CustomEvent(f,g):(h=document.createEvent("CustomEvent"),h.initCustomEvent(f,!!g.bubbles,!!g.cancelable,g.detail));k.dispatchEvent(h)}if(null==
c?0:null!=M(P(c,19))){e=new Zc;g=Uc(c,5,0);Ic(e,1,null==g?g:hc(g));g=Le(d.href,"nx");""!=g&&Wc(e,2,+g);g=Le(d.href,"ny");""!=g&&Wc(e,3,+g);g=Le(d.href,"bg");""!=g&&V(e,4,g);g=Le(d.href,"nm");""!=g&&Wc(e,5,+g);g=Le(d.href,"mb");""!=g&&Wc(e,6,+g);g=U(c,19);h=null!=ic(P(c,20))?Tc(c,20):null;f=Yc(e);k=a.s;e=z;e=void 0===e?window:e;var l=new gd;V(l,1,g);null!==h&&Wc(l,2,h);null!==k&&V(l,3,k);V(l,4,f);g=JSON.stringify(l);var m;null==e||null==(m=e.fence)||m.reportEvent({eventType:"click",eventData:g,destination:["buyer"]});
if(m=Jb){m=0;h=Ha(String(ye)).split(".");f=Ha("116").split(".");k=Math.max(h.length,f.length);for(l=0;0==m&&l<k;l++){var n=h[l]||"",p=f[l]||"";do{n=/(\d*)(\D*)(.*)/.exec(n)||["","","",""];p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];if(0==n[0].length&&0==p[0].length)break;m=Ia(0==n[1].length?0:parseInt(n[1],10),0==p[1].length?0:parseInt(p[1],10))||Ia(0==n[2].length,0==p[2].length)||Ia(n[2],p[2]);n=n[3];p=p[3]}while(0==m)}m=0<=m}if(m){var r;null==e||null==(r=e.fence)||r.setReportEventDataForAutomaticBeacons({eventType:"reserved.top_navigation",
eventData:g,destination:["buyer"],once:!0})}else{var v;null==e||null==(v=e.fence)||v.setReportEventDataForAutomaticBeacons({eventType:"reserved.top_navigation",eventData:g,destination:["buyer"]})}}T(a.h,16)||a.F?lf(a,b,d,c):(r="",(v=we())&&(r=v.appendClickSignals(d.href)),mf(a,b,d,c,r))}}}}
function jf(a,b,c,d){if(a.A===b&&a.B){var e=new ad(a.B),g=U(d,9),h="";switch(Uc(e,4,1)){case 2:if(Tc(e,2))h="blocked_fast_click";else if(U(e,1)||U(e,7))h="blocked_border_click";break;case 3:var f=void 0===f?Y:f;h=f.getElementById?f.getElementById("common_15click_anchor"):null;f=window;if("function"===typeof f.copfcChm&&h){d=Fc(d);Ic(d,5,hc(12));Pc(d,4).set("nb",(12).toString());var k=hf(a.g,h);k?k.data=d:a.g.push({element:h,data:d});!a.N&&c&&(kf(a,b,c,d),V(d,2,c.href));f.copfcChm(b,ze(d,h.href),null,
Jc(e,$c,10)?Yc(S(e,$c,10)):null);a.N&&kf(a,b,h,d)}h="onepointfiveclick_first_click"}g&&h&&Ke(g+"&label="+h,!1);Kd(a.G)}}
function lf(a,b,c,d){var e,g,h;ya(new xa(new ta(function(f){switch(f.g){case 1:e="";g=we();if(!g){f.g=2;break}b.preventDefault();var k=g.appendClickSignalsAsync(c.href);f.g=3;return{value:k};case 3:e=f.m||"";if(!a.F){f.g=2;break}a.V?f=f.return():(k=g.getNativeClickMeta(),f.g=5,f={value:k});return f;case 5:if(h=f.m){if(h.customClickGestureEligible)return f.return();e=De(e,"nas",h.encodedNas)}case 2:mf(a,b,c,d,e),f.g=0}})))}
function mf(a,b,c,d,e){var g=T(a.h,2),h=g&&300<Date.now()-a.H,f=we();f?(td(b),function(){var k=T(d,13)?e:f.logScionEventAndAddParam(e);if(!a.u&&d&&Jc(d,X,12)){var l=S(d,X,12).K();if(0<Qc(d).length)for(var m=w(Qc(d)),n=m.next();!n.done;n=m.next());T(S(d,X,12),2)?(f.click(k),f.openAndroidApp(l),l=!0):l=!1}else l=!1;if(!l&&!He(a.m,d,k,f,a.W)){l=a.Y;m=a.u;n=a.X;var p=T(d,15),r=Ce(k);!g||!h||p&&r||(k=(void 0===n?0:n)?Je(k):Je(k,f.click));k&&k.startsWith("intent:")?f.openIntentOrNativeApp(k):l?m?f.openBrowser(k):
f.openChromeCustomTab(k):f.openSystemBrowser(k,{useFirstPackage:!0,useRunningProcess:!0})}}()):(b=window,a.U&&b.pawsig&&"function"===typeof b.pawsig.clk?b.pawsig.clk(c):h&&(b=null!=c.getAttribute("attributionsrc")&&"6"===rd(c.getAttribute("attributionsrc"),"nis")?Je(c.href,function(){}):Je(c.href),b!==c.href&&nd(c,Nd(b,Od(599)))));h&&(a.H=Date.now());Kd(a.G)}
function kf(a,b,c,d){if(!T(d,13)){var e=c.href;var g=/[?&]adurl=([^&]+)/.exec(e);e=g?[e.slice(0,g.index),e.slice(g.index)]:[e,""];for(nd(c,Nd(e[0],Od(557)));!c.id;)if(g="asoch-id-"+(Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^Date.now()).toString(36)),!Y.getElementById(g)){c.id=g;break}g=c.id;"function"===typeof window.xy&&window.xy(b,c,Y.body);"function"===typeof window.mb&&window.mb(c);"function"===typeof window.bgz&&window.bgz(g);"function"===
typeof window.ja&&window.ja(g,d?Uc(d,5,0):0);"function"===typeof window.vti&&window.vti(c);a.i&&"function"===typeof window.ss&&(a.I?window.ss(g,1,a.i):window.ss(a.i,1));0<e.length&&(a=0<a.s.length&&(null==d||null==M(P(d,19)))?c.href+"&uach="+encodeURIComponent(a.s)+e[1]:c.href+e[1],nd(c,Nd(a,Od(557))))}}function nf(a){xd(ue(556,function(){new ef(a||{})}))}function hf(a,b){return Pa(a,function(c){return c.element===b})}
function ff(a){a=w(a);for(var b=a.next();!b.done;b=a.next()){var c=b.value;"A"==c.element.tagName&&(b=c.element,c=c.data,null==M(P(c,2))&&V(c,2,b.href))}};var of=ue(555,function(a){return nf(a)});Hd=70;var pf=Jd(70);if(null==pf)throw Error("JSC not found 70");for(var qf={},rf=pf.attributes,sf=rf.length-1;0<=sf;sf--){var tf=rf[sf].name;0===tf.indexOf("data-jcp-")&&(qf[tf.substring(9)]=rf[sf].value)}of(qf);}).call(this);
